"""booking table

Revision ID: 0ab6558da7d9
Revises: 350e101eb6f1
Create Date: 2026-08-22 08:47:37.273410

"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# Identificadores de revisión, usados por Alembic.
revision: str = '0ab6558da7d9'
down_revision: str | None = '350e101eb6f1'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('booking',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=43), nullable=False),
    sa.Column('reference', sa.String(length=9), nullable=False),
    sa.Column('appointment_type_id', sa.Integer(), nullable=False),
    sa.Column('customer_name', sa.String(length=200), nullable=False),
    sa.Column('customer_email', sa.String(length=255), nullable=False),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=20), server_default=sa.text("'confirmed'"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    postgresql.ExcludeConstraint((sa.text("tstzrange(starts_at, ends_at, '[)')"), '&&'), where=sa.text("status != 'cancelled'"), using='gist', name='no_overlapping_bookings'),
    sa.CheckConstraint("status IN ('confirmed', 'cancelled')", name=op.f('ck_booking_status_allowed')),
    sa.CheckConstraint('ends_at > starts_at', name=op.f('ck_booking_range_ordered')),
    sa.ForeignKeyConstraint(['appointment_type_id'], ['appointment_type.id'], name=op.f('fk_booking_appointment_type_id_appointment_type')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_booking')),
    sa.UniqueConstraint('reference', name=op.f('uq_booking_reference')),
    sa.UniqueConstraint('token', name=op.f('uq_booking_token'))
    )
    op.create_index(op.f('ix_booking_starts_at'), 'booking', ['starts_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_booking_starts_at'), table_name='booking')
    op.drop_table('booking')
    # ### end Alembic commands ###
