"""domain configuration tables

Revision ID: 350e101eb6f1
Revises: 3168153d1c43
Create Date: 2026-08-21 15:06:06.083851

"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '350e101eb6f1'
down_revision: str | None = '3168153d1c43'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('appointment_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('buffer_minutes', sa.Integer(), server_default=sa.text('15'), nullable=False),
    sa.Column('min_notice_hours', sa.Integer(), server_default=sa.text('12'), nullable=False),
    sa.Column('max_advance_days', sa.Integer(), server_default=sa.text('60'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('sort_order', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('buffer_minutes BETWEEN 0 AND 240', name=op.f('ck_appointment_type_buffer_range')),
    sa.CheckConstraint('duration_minutes BETWEEN 5 AND 480', name=op.f('ck_appointment_type_duration_range')),
    sa.CheckConstraint('max_advance_days BETWEEN 1 AND 365', name=op.f('ck_appointment_type_max_advance_range')),
    sa.CheckConstraint('min_notice_hours >= 0', name=op.f('ck_appointment_type_min_notice_non_negative')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_appointment_type')),
    sa.UniqueConstraint('slug', name=op.f('uq_appointment_type_slug'))
    )
    op.create_table('availability_exception',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_available', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('reason', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('ends_at > starts_at', name=op.f('ck_availability_exception_range_ordered')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_availability_exception'))
    )
    op.create_index(op.f('ix_availability_exception_starts_at'), 'availability_exception', ['starts_at'], unique=False)
    op.create_table('availability_rule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('weekday', sa.Integer(), nullable=False),
    sa.Column('starts_at_local', sa.Time(), nullable=False),
    sa.Column('ends_at_local', sa.Time(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('ends_at_local > starts_at_local', name=op.f('ck_availability_rule_local_range_ordered')),
    sa.CheckConstraint('weekday BETWEEN 0 AND 6', name=op.f('ck_availability_rule_weekday_range')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_availability_rule')),
    sa.UniqueConstraint('weekday', 'starts_at_local', name=op.f('uq_availability_rule_weekday_starts_at_local'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('availability_rule')
    op.drop_index(op.f('ix_availability_exception_starts_at'), table_name='availability_exception')
    op.drop_table('availability_exception')
    op.drop_table('appointment_type')
    # ### end Alembic commands ###
